### `seatools.retry` 重试工具
1. `seatools.retry.Retry`, `seatools.retry.AsyncRetry` - `class`: 重试工具, 示例

```python
import asyncio
from seatools.retry import Retry, AsyncRetry
from loguru import logger

_retry = Retry(max_attempts=10,  # 最大重试次数
               delay=10,  # 每次重试的等待间隔, 单位秒
               log_enable=True,  # 是否打印日志
               ever_fail_level='WARNING',  # 每次任务失败记录的日志级别(未达到重试上限),
               fail_level='ERROR',  # 任务重试达到失败上限的日志级别
               )

_async_retry = AsyncRetry(max_attempts=10,  # 最大重试次数
                          delay=10,  # 每次重试的等待间隔, 单位秒
                          log_enable=True,  # 是否打印日志
                          ever_fail_level='WARNING',  # 每次任务失败记录的日志级别(未达到重试上限),
                          fail_level='ERROR',  # 任务重试达到失败上限的日志级别
                          )
cnt = 0


def fail3(a: int, b: int):
    logger.info('请求参数a: {}, b: {}', a, b)
    global cnt
    if cnt < 3:
        cnt += 1
        raise Exception('异常')
    logger.info('cnt: {}', cnt)
    return cnt


# 函数调用方式, print: 3
print(_retry.do(fail3, 111, b=2))
cnt = 0


# 装饰器方式, return: 3
@_retry.retry
def fail3_wrapper(a: int, b: int):
    logger.info('请求参数a: {}, b: {}', a, b)
    global cnt
    if cnt < 3:
        cnt += 1
        raise Exception('异常')
    logger.info('cnt: {}', cnt)
    return cnt


cnt = 0
async def async_fail3(a: int, b: int):
    logger.info('请求参数a: {}, b: {}', a, b)
    global cnt
    if cnt < 3:
        cnt += 1
        raise Exception('异常')
    logger.info('cnt: {}', cnt)
    return cnt


# 函数调用方式, print: 3
print(asyncio.run(_async_retry.do(async_fail3, 111, b=2)))


cnt = 0
# async装饰器方式, return: 3
@_async_retry.retry
async def fail3_wrapper(a: int, b: int):
    logger.info('请求参数a: {}, b: {}', a, b)
    global cnt
    if cnt < 3:
        cnt += 1
        raise Exception('异常')
    logger.info('cnt: {}', cnt)
    return cnt


```
